[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"
