[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true