backend:
  name: github
  repo: darindimitroff/netlify-cms-template # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "dist/img" # Folder where user uploaded files should go
public_folder: "dist" # CMS now knows 'source' is the public folder and will strip this from the path

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "/site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  # - name: "settings"
  #   label: "Settings"
  #   files:
  #     - name: "general"
  #       label: "General settings"
  #       file: "_settings/general.json"
  #       fields:
  #         - {label: "Main site title", name: "site_title", widget: "string"}
  #         - {label: "Number of fronpage posts", name: "post_count", widget: "number"}
  #         - {label: "Site cover image", name: "cover", widget: "image"}
